### ISSUE TITLE
Keypoint/Description combination evaluation

### ISSUE THREAD

**Issue by gtinchev** [yewzijian/3DFeatNet#4] opened 2019-03-05 12:23 UTC
Hi,

I'm trying to generate Fig 4. based on the data you have provided (your keypoint extraction + your descriptor).
Am I correct in assuming the data for testing is the **test models** you have provided with the ground truth alignment?
Also, have you used the provided checkpoint for the evaluation?
Would you provide the script for generating the Precision/Meter curve? 

Please correct me if I'm wrong - as far as I understand the meters in Fig 4. refer to the distance between the selected nearest neighbour in the second cloud and the projected ground truth location of the original keypoint.

Therefore, in order to generate the plot you need to:
```
1. Detect keypoints in all clouds from **test_models**
2. For each line in groundtruth.txt:
        for kp in (each keypoint in left cloud):
            nn_second_kp = find the closest neighbour in feature space to all the keypoints in second cloud.
            projected_gt = project kp given gt transform
            distance_in_3d_space = projected_gt - nn_second_kp
            correct_match=1
```
When would you consider an incorrect match if that's the case?

Many thanks,
Georgi

**Comment by yewzijian** [comment] 2019-03-06 08:24
Hi,

1. Yes the test models are used for generating Fig. 4.

2. Yes, the provided checkpoint is the one used, but do run inference.py without the `--randomize_points` flag to reproduce the results (the point ordering in the test point clouds is already randomized).

3. I have just committed the scripts for generating the curve in fig. 4, do take a look:

	Run inference.py like this:
	`python inference.py --data_dir=<path_to_test_models> --output_dir=./test_results/f3d_d32 --checkpoint=./ckpt/checkpoint.ckpt`

	Then run the matlab scripts in order to generate the graph:
	- `scripts/fig4_step1.m` (do set the DATA_FOLDER to point to the test models, as well as RESULT_FOLDER and ALGO if you chose a different output_dir above)
	- `scripts/fig4_step2.m`

4. Yes, the distance in Fig. 4 refers to the distance between keypoint1 and T * keypoint2, where transform is the groundtruth transformation. I consider all nearest matches to all keypoints in point cloud 1, since we won't know whether matches are correct. However, I only consider the matches if a keypoint1 lies within the region of intersection of the two point clouds to not penalize detecting keypoints which does not have a correct match in a first place. I do this by checking whether keypoint1 has a point (note: not keypoint) in the (transformed) point cloud 2 within 0.75m.

Let me know if you encounter any problems.

Regards,
Zi Jian

**Comment by gtinchev** [comment] 2019-03-06 10:25
Hi Zi Jian,

That was very helpful and worked like a charm.
Would you be able to give me more information about generating the matching error at 95% recall metric/data?
Specifically:
1. I'm assuming the data refers to **clusters**.
2. There are 60000 files, instead of 30000, each file has _0 and _1 appended. Do the filenames correspond to fname1 and fname2?
3. If 2 is true, what do _0 and _1 refer to? For example, if you have the line: 

```
21      268.bin 454.bin -17.0616284886592       6.2714325591634 0.0191204883158207      -15.2106393077908       -1.09290614439235       -0.641949474811554      654     615     1
```

Then 268_1.bin and 454_1.bin are a match.
Then 268_0.bin and 454_0.bin are a match.

Another example line:

```
15798   198.bin 289.bin 24.5387358572424        13.6363164541996        0.553426027297974       10.0779790564713        -10.1145212218569       -1.14649701118469       377     468     0
```

Then 198_0.bin and 289_0.bin are not a match.
Then 198_1.bin and 289_1.bin are not a match.


4. Alternatively, if 2 is not true - does the file name refer to _idx_ in _filenames.txt_ ?
5. if 4 is true, do _0 correspond to the first filename and _1 to the second filename? For example if you have the line:

```
21      268.bin 454.bin -17.0616284886592       6.2714325591634 0.0191204883158207      -15.2106393077908       -1.09290614439235       -0.641949474811554      654     615     1
```

Then 21_0.bin and 21_1.bin are a match (here 21_0 refers to 268.bin fname1, and 21_1 refers to 454.bin)

Another example line:

```
15798   198.bin 289.bin 24.5387358572424        13.6363164541996        0.553426027297974       10.0779790564713        -10.1145212218569       -1.14649701118469       377     468     0
```

Then 15798_0.bin and 15798_1.bin are not a match (here 15798_0 refers to 198.bin fname1, and 15798_1 refers to 289.bin)

Apologies if this is confusing, hopefully it makes sense!

Cheers,
Georgi

**Comment by yewzijian** [comment] 2019-03-06 10:39
Hi, oops I noticed that the filenames.txt file might be a bit confusing. But all you need is the first and last column (the rest just indicates where I extracted the clusters from).

Assuming you have a line:
`0	642.bin	268.bin	0.730879622376105	-8.38915233275483	0.358500212430954	-1.54080077599052	-7.66297493498476	0.374484360218048	549	606	1`
This means that 0_0 and 0_1 are a match.

Similarly, if you have:
`29995	127.bin	325.bin	5.63254047466939	-14.875931253383	4.49830532073975	-13.1589897027097	12.0986747769177	2.85513925552368	488	400	0`

This means that 29995_0.bin and 29995_1.bin are *not* a match.

But anyway, the clusters are sorted such that the first 15000 pairs are matches and the next 15000 pairs are not. To compute the matching error, 1) compute the descriptor distance threshold such that 95% of the correct pairs are accepted, then 2) compute the false alarm rate at this distance threshold.


Regards,
Zi Jian

**Comment by gtinchev** [comment] 2019-03-06 14:07
Hi,

Everything worked. I was able to reproduce the results from the paper.
Thank you so much for your cooperation. 

Well done for all the hard work, I really enjoyed the paper.

**Comment by yewzijian** [comment] 2019-03-15 09:16
Glad to know that! Will be closing the issue, feel free to reopen if there's anything.

**Closed as completed by yewzijian** 2019-03-15 09:16 UTC

**Comment by Jarrome** [comment] 2020-01-30 12:47
Hi, Zi Jian,

Actually for each cluster, they are batch of points around one keypoint. So where to know the position of that keypoint? 

For example,`0	642.bin	268.bin	0.730879622376105	-8.38915233275483	0.358500212430954 -1.54080077599052	-7.66297493498476	0.374484360218048	549	606	1`, 
does `0.730879622376105	-8.38915233275483	0.358500212430954` the xyz of kp in 0_0.bin 
and `-1.54080077599052	-7.66297493498476	0.37448436021804` the xyz of kp for 0_1.bin?


Or is it (0,0,0)?

**Comment by yewzijian** [comment] 2020-01-30 13:14
For the clusters dataset, it's centered such that the keypoint is at (0, 0, 0).
You should only need the value of the last column, which states whether the pair is a match (1) or not (0). The coordinates you pointed out are the coordinates in the original point cloud which you shouldn't need.

**Comment by Jarrome** [comment] 2020-01-30 14:18
Cool, thanks a lot.
